### PR TITLE
Fix Zend_Session_SaveHandler_DbTable->write triggering warning

### PR DESCRIPTION
**Pull request by Dringho**
Mute warning when using Zend_Session_SaveHandler_DbTable.

### CODE REVIEW

**Comment by Shardj** [comment]
Hi, what warning are you getting? It's better for you to simply fix warnings rather than supress them.

**Comment by Dringho** [comment]
@Shardj I took the time to find and fix the bug in the best possible way. In this case, the chain of events is

Zend_Session_SaveHandler_DbTable->_destruct triggers Zend_Session::writeClose
writeClose triggers a write in `Zend_Session_SaveHandler_DbTable` through `session_write_close`
if the data being updated matches the one in the database, the update returns 0, which returns false in turn, and then `session_write_close` triggers the `Failed to write session data using user defined save handler.` error as explained in https://stackoverflow.com/questions/43636109/php7-session-warning-session-write-close (Started happening in PHP 7).

If there is an error on the configuration, the update will throw an exception instead of returning 0.

**Comment by Shardj** [comment]
Alright, thanks. This is an annoying php 7 change. But since try catch for Zend_Session_SaveHandler_Exception should be used to detect issues when writing data anyway it's acceptable. I'll tag this as a major change as it can possibly change functionality for some people.

**Comment by Shardj** [comment]
Sorry wrong button there

**Comment by Shardj** [comment]
This is now part of release-1.15.0

**Pull request merged**
