### PR TITLE
added setting to disable automatic strigify of pdo mysql

### PR DESCRIPTION
**Pull request by roshanbudhathoki**
Fixes https://github.com/Shardj/zf1-future/issues/362 as prescribed by 

[hungtrinh](https://github.com/hungtrinh)

### CODE REVIEW

**Comment by develart-projects** [comment]
@roshanbudhathoki seems like some Unit tests are failing after the change. Could you pls review?

**Comment by roshanbudhathoki** [comment]
@develart-projects  I am getting following error.

Testing fetchLatersVersion only works when TESTS_ZEND_VERSION_ONLINE_ENABLED is set.

Am I missing to setup something. Even unsure where do I setup this.

**Comment by develart-projects** [comment]
@roshanbudhathoki  here is my local testing command:

```
php /usr/share/NetBeansProjects/ZF1-Future/bin/phpunit --colors --log-junit /var/tmp/nb-phpunit-log.xml --configuration /usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml /usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php
```

**Comment by roshanbudhathoki** [comment]
@develart-projects  I have fixed and updated the code, should work now. Please approve so that CI can run and give us the test results.

**Pull request merged**
