### PR TITLE
Initial PHP 8.2 fixes

### PR DESCRIPTION
**Pull request by VentyCZ**
PHP 8.2 release is closing in and this PR is fixing some of the warnings (all encountered during the initial testing of our application) that are present when running zf1-future under PHP 8.2.

Will update, if any other warnings/errors arise. Currently, fixes only "Creation of dynamic property ..." warnings.

Any notes are appreciated!

### CODE REVIEW

**Comment by dscheinah** [comment]
I just updated one of my projects to shardj/zf1-future:dev-master and encounter new warnings:
`Warning: Undefined variable $name in /var/www/src/vendor/shardj/zf1-future/library/Zend/Form/Element.php on line 1008`

That seems to be introduced with this PR.

**Comment by VentyCZ** [comment]
Nice catch! Wrong variable name on that line, should be $key not $name.
Can you make a PR for this, or anything else you might find @dscheinah?

**Comment by Shardj** [comment]
Thanks for the find @dscheinah

**Comment by dscheinah** [comment]
I started to write the fix and found another problem with the changes in the `Zend_Form_Element` class. Unfortunately I'm not sure on how to deal with it.
Derived classes (like Multiselect) assume that attributes and public properties (without `_`) are interchangeable. With the new code, setting `$multiple` and `$helper` has no effect.
To ensure backward compatibility it should still work. But for that we would need to somehow merge the old and new code. That sounds somewhat ugly...
Do you have any opinion or ideas on that?

**Comment by VentyCZ** [comment]
@dscheinah I see what you're saying. This should be resolved by using these properties, if they exist (check with property_exists before using _attributes). Will try to create another PR which resolves this, I'm sorry for these issues.

**Comment by VentyCZ** [comment]
@dscheinah @Shardj PR #268 should fix all the introduced issues (+ #267), let's continue there.

**Pull request merged**
