### PR TITLE
Update HeaderValue.php

### PR DESCRIPTION
**Pull request by icyz**
header validation with RFC 6532 instead of RFC 2822

### CODE REVIEW

**Comment by develart-projects** [comment]
Please adjust the tests to cover the new testing:

 There were 6 failures:

1) Zend_Mail_Header_HeaderValueTest::testValidateValue with data set #4 ('This is a \r\ntest', 'assertFalse')
Failed asserting that true is false.

/home/runner/work/zf1-future/zf1-future/tests/Zend/Mail/Header/HeaderValueTest.php:85
/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

2) Zend_Mail_Header_HeaderValueTest::testValidateValue with data set #9 ('This is a \r\n\r\ntest', 'assertFalse')
Failed asserting that true is false.

/home/runner/work/zf1-future/zf1-future/tests/Zend/Mail/Header/HeaderValueTest.php:85
/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

3) Zend_Mail_Header_HeaderValueTest::testAssertValidRaisesExceptionForInvalidValues with data set #3 ('This is a \r\ntest')
Failed asserting that exception of type "Zend_Mail_Exception" is thrown.

/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

4) Zend_Mail_Header_HeaderValueTest::testAssertValidRaisesExceptionForInvalidValues with data set #8 ('This is a \r\n\r\ntest')
Failed asserting that exception of type "Zend_Mail_Exception" is thrown.

/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

5) Zend_Mail_MessageTest::testRaisesExceptionWhenProvidedWithHeaderContainingCRLFInjection with data set "value" ('Fake', 'foo-bar\r\n\r\nevilContent')
Failed asserting that exception of type "Zend_Mail_Exception" is thrown.

/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

6) Zend_Mail_MessageTest::testRaisesExceptionWhenProvidedWithHeaderContainingCRLFInjection with data set "multi-value" ('Fake', array('okay', 'foo-bar\r\n\r\nevilContent'))
Failed asserting that exception of type "Zend_Mail_Exception" is thrown.

/home/runner/work/zf1-future/zf1-future/tests/resources/Runner.php:20
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:143
/home/runner/work/zf1-future/zf1-future/tests/Zend/AllTests.php:267

**Comment by icyz** [comment]
Why did the tests fail? I'm having some issues handling unittest because I can't test directly on my local environment.

**Comment by icyz** [comment]
Can someone help with managing the tests?

**Comment by develart-projects** [comment]
This is how I'm starting the tests locally:

`php "/usr/share/NetBeansProjects/ZF1-Future/bin/phpunit" "--colors" "--configuration" "/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml" "/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php"`

**Comment by icyz** [comment]
I tested the newly downloaded project and encountered some errors...

using php 8.2
`~/zf1-future$ /bin/php8.2 bin/phpunit "--colors" "--configuration" "tests/phpunit.xml" "tests/AllTests.php" `

this is the output:
`FAILURES!
Tests: 10803, Assertions: 359229, Failures: 2, Warnings: 7, Skipped: 666, Incomplete: 13.`



using php 8.1
`~/zf1-future$ /bin/php8.1 bin/phpunit "--colors" "--configuration" "tests/phpunit.xml" "tests/AllTests.php" `
`FAILURES!
Tests: 10803, Assertions: 359560, Failures: 2, Warnings: 7, Skipped: 558, Incomplete: 16.`

**Comment by develart-projects** [comment]
I mean failures.

**Comment by icyz** [comment]
[phpunit.txt](https://github.com/user-attachments/files/18187271/phpunit.txt)

This is the full report... I hope it will be useful.

**Comment by develart-projects** [comment]
There are 2 failed translation tests, you can ignore them for now.

**Comment by develart-projects** [comment]
Pls try to fix the tests with you local change. That's enough for you PR, thanks.

**Comment by develart-projects** [comment]
(ignoring those 2)

**Review by icyz — COMMENTED** [review]
removed CRLF test because it's allowed in  RFC 5322 and 6532

**Comment by icyz** [comment]
🥳

**Pull request merged**
