### PR TITLE
Add PHPUnit 9 run on php 8.1 to Github actions, Fix some php 8.1 depricated issue

### PR DESCRIPTION
**Pull request by hungtrinh**
### Work Done

As mentioned in section [What next of PR 240](https://github.com/Shardj/zf1-future/pull/240)
- [x] Add PHPUnit 9 run on PHP 8.1 to Github 
- [x] Fixed  PHP 8.1  Deprecated warning:
   - `current(): Calling current() on an object is deprecated`
   - `Passing null to parameter #1 () of type string is deprecated`

### Unresolved problem

On php 8.1:

- [x] Function date_sunset() is deprecated
- [x] Function date_sunrise() is deprecated

```bash
❯  docker run -e CI=true --rm -v $(pwd):/app jakzal/phpqa:php8.1-alpine phpunit --bootstrap /app/tests/TestHelper.php /app/tests/Zend/AllTests.php

PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

....................S....S.......

Time: 00:30.474, Memory: 207.38 MB

There were 2 errors:

1) Zend_DateTest::testSunFunc
Function date_sunset() is deprecated

/app/library/Zend/Date/DateObject.php:929
/app/library/Zend/Date.php:3160
/app/tests/Zend/DateTest.php:3828
/app/tests/Zend/AllTests.php:139
/app/tests/Zend/AllTests.php:263

2) Zend_Date_DateObjectTest::testCalcSunInternal
Function date_sunrise() is deprecated

/app/library/Zend/Date/DateObject.php:932
/app/tests/Zend/Date/DateObjectTest.php:658
/app/tests/Zend/Date/DateObjectTest.php:280
/app/tests/Zend/AllTests.php:139
/app/tests/Zend/AllTests.php:263

ERRORS!
Tests: 9275, Assertions: 39641, Errors: 2, Skipped: 449, Incomplete: 13.
```

@PHPGangsta Could you please resolve this issue? I guess you have a lot of experience with this problem 
I try apply [this solution](https://php.watch/versions/8.1/date_sunrise-date_sunset-funcs-deprecated#alternative) into [Zend/Date/DateObject.php](https://github.com/Shardj/zf1-future/blob/master/library/Zend/Date/DateObject.php#L927-L932) but test case [DateObjectTest::testCalcSunInternal](https://github.com/Shardj/zf1-future/commit/475423605531f212ec0d5a69cc6c697e2db5cc72) will failed

### CODE REVIEW

**Comment by Jimbolino** [comment]
i've done some digging, and the original test code was copied from @jaydiablo
https://github.com/diablomedia/zf1-date/commit/f69acaf6bc563af898144abd0a8aa1bbbf0e0308

also the calcSun function is wrongly documented:
``` 
     * @param  array  $location  Location for calculation MUST include 'latitude', 'longitude', 'horizon'
     * @param  bool   $horizon   true: sunrise; false: sunset
     * @return mixed  - false: midnight sun, integer:
```
So if people put true/false there, the $zenith will be 90+true or 90+false

The main difference between date_sunset / date_sun_info is the $zenith / $horizon parameter.
By switching to date_sun_info we lose the support for a custom zenith angle, which i think is fine.

I'm not sure why the zf1 devs used 90-0.0145439 = 89,9854561 as the zenith for their tests.

The default should be [float 90.833 aka 90°50'](https://www.php.net/manual/en/function.date-sunrise.php#:~:text=Sunrise%3A%20the%20point%20where%20the%20sun%20becomes%20visible.) 
https://3v4l.org/b9LFD

I dont believe there are people actually depending on this code, for exact sunset/sunrise times, so worst case there is a 1-5 min difference between versions.

**Comment by hungtrinh** [comment]
@Jimbolino thanks for your help, in this situation to keep backward compatibility with php < 8.1 i added new case for php >= 8.1, keep old code for php < 8.1

### Resolved problem
On php 8.1:

- [x] Function date_sunset() is deprecated so replace by [date_sun_info()](https://github.com/hungtrinh/zf1-future/blob/ci-phpunit-on-php81/library/Zend/Date/DateObject.php#L927-L932)
- [x] Function date_sunrise() is deprecated so replace by [date_sun_info()](https://github.com/hungtrinh/zf1-future/blob/ci-phpunit-on-php81/library/Zend/Date/DateObject.php#L927-L932)
- [x] Add test data for php 8.1 [DateObjectTest::testCalcSunInternal()](https://github.com/hungtrinh/zf1-future/blob/ci-phpunit-on-php81/tests/Zend/Date/DateObjectTest.php#L279-L295) 
 - [x] Add test data for php 8.1 [DateTest::testSunFunc()](https://github.com/hungtrinh/zf1-future/commit/37b5e02d3d6a7846897192a4d39c9075418a4af1)

**Comment by Jimbolino** [comment]
you accidentally added a .sqlite file :)

**Comment by hungtrinh** [comment]
> you accidentally added a .sqlite file :)

Thanks ^^ @Jimbolino don't worry about it. Everytime i run full test on my pc this fixture sqlite file changed but without any ill effect.

**Pull request merged**
