### PR TITLE
[zend-progressbar] fix "stty: 'standard input': Inappropriate ioctl for device" spam

### PR DESCRIPTION
**Pull request by hungtrinh**
Carries zf1s/zf1#155 which was created by @falkenhawk 

fix Inappropriate ioctl for device spam

### CODE REVIEW

**Comment by hungtrinh** [comment]
Mr @glensc could you please review this PR

**Comment by glensc** [comment]
@hungtrinh  LGTM

but you could preserve the original author and commit date with `git commit --amend --author "Name Email" --date "Date Header Value from git show"`

I personally try first with export the commit with `git format-patch -1 SHA` from original repo and in the other repo `git am 0001-the-commit.patch`, manually apply `.patch` with `patch` program or manually resolve conflicts, and `git add -p` or `git add` followed by `git am --continue` 

I'll leave you to try this, or do it myself some days later.

**Comment by hungtrinh** [comment]
i tried apply patch but not success so i used `git commit --amend --author "Name Email" --date "Date Header Value from git show"`

Mr @glensc do have experiences about `Unknown or bad timezone` on linux? 

i'm investigating about randomly issue:
- https://github.com/Shardj/zf1-future/actions/runs/3889198864/jobs/6637260265#step:7:253
- https://github.com/Shardj/zf1-future/actions/runs/3877247719/jobs/6612044203#step:7:411

**Comment by hungtrinh** [comment]
Oops, About `Unknown or bad timezone`  is internal bug of php/php-src/issues/10218

**Comment by glensc** [comment]
well, i hope you didn't use the git command literally but actually replaced the placeholders with intended values. do show actual command and actual error you had

**Comment by glensc** [comment]
The author and date seem ok:
- https://github.com/Shardj/zf1-future/pull/303.patch

**Comment by glensc** [comment]
CI errors seem unrelated to this, so merging

**Comment by glensc** [comment]
the date problem has already issue in this repo:
- https://github.com/Shardj/zf1-future/issues/304

**Comment by hungtrinh** [comment]
> well, i hope you didn't use the git command literally but actually replaced the placeholders with intended values. do show actual command and actual error you had

That's my fail
After download https://patch-diff.githubusercontent.com/raw/zf1s/zf1/pull/155.patch i run cmd:

```
$~/Projects/zf1-future
git apply -p 3 ~/Downloads/155.patch 

error: patch failed: library/Zend/ProgressBar/Adapter/Console.php:243
error: library/Zend/ProgressBar/Adapter/Console.php: patch does not apply
```

After see your 303.patch
Next time i will do that and resolve conflict:
```
$~/Projects/zf1-future
git apply -p3 -3  ~/Downloads/155.patch

Applied patch to 'library/Zend/ProgressBar/Adapter/Console.php' with conflicts.
U library/Zend/ProgressBar/Adapter/Console.php
```

**Pull request merged**
