### PR TITLE
Mail via SMTP: added verify_peer and verify_peer_name configuration parameters

### PR DESCRIPTION
**Pull request by francescozanoni**
I've added these two parameters (mapping PHP's [SSL context options](https://www.php.net/manual/en/context.ssl.php) with same names):
```ini
resources.mail.transport.verify_peer = true/false/1/0
resources.mail.transport.verify_peer_name = true/false/1/0
```

in order to avoid this error with self-signed certificates:
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (/path/to/shardj/zf1-future/library/Zend/Mail/Protocol/Smtp.php:<line containing stream_socket_enable_crypto>)
```

Reference: https://stackoverflow.com/questions/32211301/ssl-error-ssl3-get-server-certificatecertificate-verify-failed#32366242

### CODE REVIEW

**Comment by glensc** [comment]
at looking at the diff, seems illogical to set verify_peer and verify_peer_name options after connection already has been made. perhaps the connect method doesn't really connect but returns an un-connected resource, but then that's another flaw that the method name does not match its logic.

ps: you should't create pull requests from your master branch: `francescozanoni:master`

**Comment by glensc** [comment]
the more logical place to set this is in the abstract class like other options are set on the unconnected socket:
- https://github.com/Shardj/zf1-future/blob/release-1.18.9/library/Zend/Mail/Protocol/Abstract.php#L280

**Comment by francescozanoni** [comment]
I perfectly agree, I was misled by the abstract connect() method.
I'll move everything to Zend_Mail_Protocol_Abstract::_connect().
Thanks, man!

**Comment by francescozanoni** [comment]
And I'll close this PR, to create a new one from a specific branch.

**Pull request closed without merging**
