### PR TITLE
WIP: PHP 8.0 Travis CI / unit test fixes

### LINKED ISSUE #131: Set up Travis CI and update it to test up to PHP 8

### PR DESCRIPTION
**Pull request by onlime**
backported some Travis CI / phpunit fixes from https://github.com/zf1s/zf1
so far completely WIP and untested!

Fixes #131

UPDATE: This is just a backport of zf1s/zf1@8eb04b2977e173ee614ca86761bc63057d4f2724 by @Megatherium and some Travis / unittest enhancements by @falkenhawk and @glensc - thanks for the great work!

### CODE REVIEW

**Comment by glensc** [comment]
@onlime you should give credits to commits ported, i.e tag appropriate persons with their `@handle` in PR body and possibly linking to pull request the changes came from.

**Comment by onlime** [comment]
> @onlime you should give credits to commits ported, i.e tag appropriate persons with their `@handle` in PR body and possibly linking to pull request the changes came from. and perhaps even cherry-pick the commits to preserve author and commit metadata, or fix them later with it `git commit --amend --author '' --date ''`.

you're right. I had already linked the commit in https://github.com/Shardj/zf1-future/issues/131#issuecomment-774951871, now updated this PR description. It's a bit hard to mention `@Alexander Wozniak` with a space in his username and I am running out of time on this, so hope you understand. We greatly appreciate your work on zf1s!

**Comment by glensc** [comment]
@onlime his handle is @Megatherium which you can see from the PR itself:
-  https://github.com/zf1s/zf1/pull/42

**Comment by glensc** [comment]
no offense, but @onlime, you have saved tons of time by using the work of some other person, so running out of time excuse is not proportional!

if you need more help, I'm happy to help with git/GitHub fu!

**Comment by glensc** [comment]
@onlime, `Fixes #31` seems an invalid reference.

**Comment by onlime** [comment]
@glensc pls tell me what else needs to be done here to make you guys happy. Cherry-picking of those commits was not possible in that case, as this project's codebase has diverged too much form zf1s/zf1. Let me know if you still want me to rewrite commits, but in that case you would need to provide me with exact commands and what you wish to be in the commit message. I don't want to make another mistake. All I wanted was contribute to the community and I spend several hours on #130 + #131. So please don't call it "you have saved tons of time". Maybe I have saved other's time, but definitely not mine.
I am in no rush to get my legacy project running on PHP 8. It just felt like @Shardj can use some extra hand here. I was never supposed to "steal" someone else's work. All credits go to you guys.

**Comment by Shardj** [comment]
Woah there guys, lets keep it friendly. @glensc @onlime is contributing to the community, he didn't save his own time, he contributed it. Hell I don't even know how to cherry pick commits over to conserve the original author or whatever is wanted here either and I would've made the exact same mistake since I often don't bother with PR's anyway. 

@onlime thanks for the work you've done here, it's very helpful. We're both now clear on giving credit to original authors of commits.

@glensc thanks for bringing it up, you're right that it's important to give credit where credit is due. Your contributions to this repo are also very much appreciated. I'll make sure to be better with this in the future too.

**Comment by Shardj** [comment]
I've not used Travis before and after skimming through the PR I can't see any problems

**Comment by onlime** [comment]
Yes, I will definitely be more careful crediting others correctly next time! @glensc gave us a lesson here and he is right.

@Shardj Thanks for accepting this PR, but it was not meant to be merged yet into `master`, as I explicitely put a `WIP:` prefix in its title and I am quite sure Travis CI will work yet correctly like this (on the other hand it will also not break any existing code, so don't worry about that). I don't see any Travis pipelines running, so I think you also need to set up Travis CI on your project first, otherwise `.travis.yml` is not getting picked up at all.

I would recommend to first start running phpunit tests locally on your dev machine and then dig into Travis CI. Again, I cannot really help you here as I could not get unit tests running yet with that setup of outdated phpunit. And I have never set up Travis CI on Github before. @glensc if you can give @Shardj some hints, we would definitely appreciate!

**Comment by Shardj** [comment]
@onlime I guess I just learnt another lesson about not looking at PR's properly. But Travis CI isn't set up yet anyway as you pointed out so I wouldn't worry about the fact it's not currently in a working state in master. I've also never set up Travis CI before, I mainly use CircleCI, but I'm sure it won't be a problem.

**Comment by falkenhawk** [comment]
heads up: travis is no good anymore (the builds are not even running since 2 months - https://travis-ci.com/github/zf1s/zf1 - https://github.com/zf1s/zf1/pull/44#discussion_r555717634) and @glensc is putting great efforts into migrating the pipelines to Github Actions in https://github.com/zf1s/zf1/pull/34 🙏

**Comment by Shardj** [comment]
@falkenhawk thanks for the info :+1:

**Comment by glensc** [comment]
@onlime you should use GitHub Draft status so the maintainers can't merge before the branch is ready from the contributor side:
- https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by onlime** [comment]
> @onlime you should use GitHub Draft status so the maintainers can't merge before the branch is ready from the contributor side:
> 
>     * https://github.blog/2019-02-14-introducing-draft-pull-requests/

oh, ok, thanks for the hint. I'm just too much into GitLab where draft status is auto-detected from `Draft:` or `WIP:` prefix in MR title. I'll remember next time.

**Comment by glensc** [comment]
@onlime my post started with "no offense", so it was not to be taken offensive. what I was saying is that you didn't took the work from zf1s project, you would had spend same amount fixing the codebase yourself.

right now the people whose code was pulled, are mentioned, so they should be happy :), and nothing more to do, as branch already merged.

**Comment by glensc** [comment]
# git-fu

for the patches that do not apply, I'll share my experience as best as I can.

1. get the patch 
	- `git format-patch -1 COMMIT`
	- or `wget`/`curl` the github PR url with `.patch` or `.diff` appended to the url
2. run `git am /path/to/the.patch`, it will error, but try to get the changes staged
    - I've used `patch -p1 < /path/to/the.patch` and manually adjusted others
3. `git add -p` or use ide to stage
4. `git amend --continue`

this usually results the expected outcome.

sometimes it's just easier to make commit, but change date/author:

1. stage the changes intended for commit
2. `git commit --author 'Author Name <email@example.com>' --date 'Date:-header-of-original-commit'`

or if you already made the commit, you can change date/author:
1. `git rebase -i <TIP_WHERE_TO_REBASE>`
  - if your commits are linear, replace `<TIP_WHERE_TO_REBASE>` with `<COMMIT>~1`
  - the tip can be also just `origin/master` or `upstream/master`, it will have more commits
2. pick `e` to edit
3. exit the editor
4. now you will be presented with terminal, use `git commit --amend --author` or `--date` to change the fields
5. `git rebase --continue` to finish up rebasing

**Comment by onlime** [comment]
> @onlime Are the additional php extensions actually required? This commit caused issues with deploys on several of our repos

Nope, they are not, as nobody is using full-fledged zf1 with all components. This MR was not yet supposed to be merged. But, @brendandebeasi why do your repos use `dev-master`?
@Shardj please remove those lines again: https://github.com/Shardj/zf1-future/blob/6411df9cb07337e823210c584e0b3e8f4d38ff52/composer.json#L13-L24

**Comment by brendandebeasi** [comment]
@onlime You are right that we shouldn't be using `dev-master`, and this is a great example of why. Going to lock our version at 1.19 for now. TY!

**Comment by Shardj** [comment]
Thanks @brendandebeasi @onlime I'll go and sort this out now

Yeah definitely don't use dev-master

**Pull request merged**
