### PR TITLE
Compatability for PHPUnit 9.0.1

### PR DESCRIPTION
**Pull request by Bloafer**
Fixes
```PHP Fatal error:  Declaration of Zend_Test_PHPUnit_ControllerTestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp()```

### CODE REVIEW

**Comment by Shardj** [comment]
It's already compatible as PHPUnit\Framework\TestCase::setUp() is a protected function

https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L416

Your change would cause the bug you've got in your description for most people rather than fixing it. Look into why your version of PHPUnit\Framework\TestCase::setUp() is different to the one I've linked. You can override the original with something like the below which is a file dump from my project.

```
<?php

define('TEST_EXECUTION', true);

require_once dirname(__FILE__) . '/../..' . '/app-loader.php';
class PHPUnit_Framework_TestCase extends \PHPUnit\Framework\TestCase {}
```

You should just be able to add
 
    ```
public function setUp() {
        
    }
```

To that

**Comment by Bloafer** [comment]
I accidently change the method to public, I have reverted this but left the `void` in to prevent the Fatal

**Comment by Shardj** [comment]
This will break compatibility to those using phpunit version 7.* or lower since it doesn't have a void return typehint at that point. And yeah looks like my code suggestion from before won't work, not sure why I thought it would at the time.

I'm not sure if I should merge this or not. On one hand I want to push for keeping this repo up to date, but on the other hand breaking unit tests for everyone who's currently using this repo (and gets the latest version) sounds quite problematic.

**Comment by Shardj** [comment]
Since there's lack of activity on this now I'm just going to make the decision to close this. The reason being I'm not comfortable with making changes that will actively break things for those using older phpunit versions (which will be nearly everyone with this repo). I recommend you override the class namespace with an exact copy of this file and the void change you need, or you use your own fork of this repo with the changes you need made there which is what I presume you're already doing.

**Comment by ikari-pl** [comment]
Thank you, @Bloafer, I have actually used this PR as a patch file in my repo.

**Comment by glensc** [comment]
@Shardj 


🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

**Comment by andrewpurkett** [comment]
For those who have chosen to upgrade to PHPUnit 8.0 or higher, it’s possible to support both scenarios, simultaneously. Please see this sample implementation of a fix that works for both scenarios from the mockery library (since removed, when mockery dropped support for phpunit < 8):

https://github.com/mockery/mockery/blob/aa0020fa143c2b06651911c872d300873f8464a4/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php#L25-L37

I can open a PR for this issue if necessary @Shardj @Bloafer

**Comment by Shardj** [comment]
@andrewpurkett sounds great, if we get the best of both worlds without breaking backwards compatibility

**Pull request closed without merging**
