### PR TITLE
Added typecast to stop depreciation messages

### PR DESCRIPTION
**Pull request by krytenuk**
Simple fix to prevent deprecation messages.

### CODE REVIEW

**Comment by glensc** [comment]
can you add a test case?

**Comment by glensc** [comment]
and perhaps rebase to remove merge commits from the branch

**Comment by krytenuk** [comment]
I got deprecation notice during an upgrade of older code to PHP8.1. I will try to reproduce and provide a test case.

**Comment by krytenuk** [comment]
I can't reproduce the deprecation notices I was seeing, looks like other changes to the code has fixed the issue.
Not sure if you still wish to use this change as it is only type casting changes, if not then I will keep my branch should the issue re-emerge.

**Comment by develart-projects** [comment]
@krytenuk seems we are now in conflict, could you pls pull latest master and review? Thank you.

**Pull request merged**
