### PR TITLE
Fixes for issues introduced by #261

### LINKED ISSUE #267: PHP 8.2 fixes commit on file library/Zend/Form/Element.php break unit test tests/Zend/Form/ElementTest.php (tests/Zend/Form/AllTest.php)
@VentyCZ  cc @Shardj  Sorry when comment on closed PR. 

Could you please help review and correct this issue @VentyCZ ?

But with this changed of [library/Form/Element.php](https://github.com/Shardj/zf1-future/pull/261/files#diff-4de0f6e712ea2a7c9a1bcd60f804afb239d82095cfa68e28e18e2946d2b4abc4) will break unit test  tests/Zend/Form/ElementTest.php (and more tests/Zend/Form/AllTests.php)  
I think this is a risk. 

This change is cause of [17 error on github action](https://github.com/Shardj/zf1-future/actions/runs/3368336468/jobs/5586764095#step:5:190)

1. it's log when i run on my computer (branch master) minimal test failed (you can run tests/Zend/Form/AllTests.php to see other Errors)
```
php8.0 ./bin/phpunit -c tests/phpunit.xml --color --testdox tests/Zend/Form/ElementTest.php
PHPUnit 9.5.21 #StandWithUkraine

...............................................................  63 / 170 ( 37%)
.......................................................E....... 126 / 170 ( 74%)
..EEEEE.....................E...............                    170 / 170 (100%)

Time: 00:00.019, Memory: 10.00 MB

There were 7 errors:

1) Zend_Form_ElementTest::testAddingConcreteDecoratorShouldHonorOrder
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1428
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

2) Zend_Form_ElementTest::testRenderElementReturnsMarkup
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1565
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

3) Zend_Form_ElementTest::testRenderElementRendersLabelWhenProvided
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1577
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

4) Zend_Form_ElementTest::testRenderElementRendersValueWhenProvided
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1590
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

5) Zend_Form_ElementTest::testRenderElementRendersErrorsWhenProvided
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1608
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

6) Zend_Form_ElementTest::testToStringProxiesToRender
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2102
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:2117
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1619
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

7) Zend_Form_ElementTest::testElementShouldOverloadToRenderDecorators
Error: Cannot instantiate abstract class Zend_View_Helper_FormElement

/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:1178
/home/trinhhung/Projects/zf1-future/library/Zend/View/Abstract.php:628
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Decorator/ViewHelper.php:242
/home/trinhhung/Projects/zf1-future/library/Zend/Form/Element.php:1034
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:1999
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:64
/home/trinhhung/Projects/zf1-future/tests/Zend/Form/ElementTest.php:2301

ERRORS!
Tests: 170, Assertions: 387, Errors: 7.
  ```

2. Here it's the way  i know this commit it's root cause

  ```
❯ git checkout 8c327b170 library/Zend/Form/Element.php
Updated 1 path from 3bec3cac3

❯ php8.0 ./bin/phpunit -c tests/phpunit.xml --color --testdox tests/Zend/Form/ElementTest.php
PHPUnit 9.5.21 #StandWithUkraine

...............................................................  63 / 170 ( 37%)
............................................................... 126 / 170 ( 74%)
............................................                    170 / 170 (100%)

Time: 00:00.017, Memory: 10.00 MB

OK (170 tests, 417 assertions)

❯ php8.0 ./bin/phpunit -c tests/phpunit.xml --color --testdox tests/Zend/Form/AllTests.php
PHPUnit 9.5.21 #StandWithUkraine

..............................S................................  63 / 914 (  6%)
............................................................... 126 / 914 ( 13%)
............................................................... 189 / 914 ( 20%)
............................................................... 252 / 914 ( 27%)
............................................................... 315 / 914 ( 34%)
............................................................... 378 / 914 ( 41%)
............................................................... 441 / 914 ( 48%)
.........I..................................................... 504 / 914 ( 55%)
............................................................... 567 / 914 ( 62%)
............................................................... 630 / 914 ( 68%)
............................................................... 693 / 914 ( 75%)
............................................................... 756 / 914 ( 82%)
.........................I..................................... 819 / 914 ( 89%)
...............I............................................... 882 / 914 ( 96%)
................................                                914 / 914 (100%)

Time: 00:00.100, Memory: 28.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 914, Assertions: 2369, Skipped: 1, Incomplete: 3.

  ```

### PR DESCRIPTION
**Pull request by VentyCZ**
This PR should fix all the issues introduced by #261.

1) Fixes typo (key != name)
2) Uses properties, if they exist

Also mostly fixes #267.

### CODE REVIEW

**Comment by VentyCZ** [comment]
@kaktusas2598 @hungtrinh I also fixed the last failing tests from PartialTest.php, is this an appropriate fix?

**Comment by Shardj** [comment]
Not sure what's up with the foo bar change in partialVars, but I'll merge anyway

**Comment by hungtrinh** [comment]
> @kaktusas2598 @hungtrinh I also fixed the last failing tests from PartialTest.php, is this an appropriate fix?

Wow, thanks for the quick fix. 

Yep, I think this is an appropriate fix when looking forward.

### For old project

Focus on the old project used method `get_object_vars($viewObject)`, I'm a little bit worried about the change in design specifications [PartialTest.php](https://github.com/Shardj/zf1-future/pull/268/commits/4ebafa445ee108de10f2871fa3400cc2a3f491b7) to fit  with the way to access properties of  [Zend_View](https://github.com/VentyCZ/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919) object 

Before we can:
1. get_object_vars($viewObject);
1. $viewObject->getVars();
1. $viewObject->yourVarName; 

Now after this change of [Zend_View_Abstract](https://github.com/VentyCZ/zf1-future/commit/34331f7faedba5f23521ee50e04bb3ff4cdb6919)

1. $viewObject->getVars();
1. $viewObject->yourVarName; 

So on old project need migrate to use `$view Object->getVars();` instead of `get_object_vars($view Object)`

### Another Approach To fix dynamic properties are deprecated on PHP 8.2

Use [AllowDynamicProperties](https://php.watch/versions/8.2/dynamic-properties-deprecated#AllowDynamicProperties) will help backward compatibility for an old project

**Comment by VentyCZ** [comment]
@hungtrinh I'd argue that an old project - which would update to the latest version of zf1-future - would probably require more changes to its code to guarantee full PHP 8.2 compatibility (as is the case with the project I'm working on, we're in process of updating from 7.4 to 8.1).

I guess it depends on the stance zf1-future might take. I'd declare this as a breaking change and let users update their code (IMHO, using get_object_vars instead of getVars() is not optimal to say the least).

I'd like to hear your opinion on this, @Shardj. I could prepare another PR which reverts most of these changes in favor of `AllowDynamicProperties` attribute, but - in my opinion - it would be a step backwards.

Anyway, thanks to @Shardj for merging both of my PRs and for continued support of ZF1 (also goes to all the other contributors to this project)!

**Pull request merged**
