### PR TITLE
[PHPUnit] migrate ./tests source from PHPUnit 3.x to PHPUnit 9.5 vs Add PHPUnit 9 to Github actions tests (test success on php 8.0, comment on php 8.1)

### PR DESCRIPTION
**Pull request by hungtrinh**
### Work done

1. Use rector/rector + manual to migrate PHPUnit from 3.6 -> 9.5
2. Temporarily disable some test suite not compatible with PHPUnit 9 
3. Apply PSR12 coding standard to ./tests folder
4. Add PHPunit 9 job to Github actions tests 

### Testing 

1. on Docker env

  ```
  docker run -t --rm -v $(pwd):/app jakzal/phpqa:php8.0-alpine phpunit --bootstrap /app/tests/TestHelper.php /app/tests/Zend/AllTests.php
  ```
2. on localhost with php 8 - composer

```
composer install 
composer test
```

### What next

1. After merged this PR, i will make other PR - Add PHPUnit 9 run on php 8.1 to Github actions, that will show many deprecated message when run unit test on php 8.1
5. Next i will make other PR to fix all depricated message showed when run phpunit 9.5 on php 8.1

### CODE REVIEW

**Comment by hungtrinh** [comment]
@Shardj how do you think about this PR ?

**Comment by develart-projects** [comment]
+1, as tests are not working at all now.

**Comment by Shardj** [comment]
@develart-projects not sure what you mean, which bit is broken for you

**Comment by Shardj** [comment]
@develart-projects are you talking about your own tests or zf1-future's tests? What error are you getting?

**Comment by Jimbolino** [comment]
I think we should merge this.
There are currently no working automated unit tests on this project. (except for some basic linting)
This would be a good starting point.

phpunit 9 has a minimum requirement for php 7.3
So I ran it locally (via docker) on php 7.3 / 7.4 / 8.0 / 8.1 / 8.2 and results are as expected.
```

docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.3-cli php -d memory_limit=256M ./bin/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
Tests: 9275, Assertions: 39550, Errors: 4, Failures: 4, Skipped: 488, Incomplete: 9, Risky: 1.

docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.4-cli php -d memory_limit=256M ./bin/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
Tests: 9275, Assertions: 39550, Errors: 4, Failures: 4, Skipped: 488, Incomplete: 9, Risky: 1.

docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.0-cli php -d memory_limit=256M ./bin/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
Tests: 9275, Assertions: 39589, Failures: 1, Skipped: 489, Incomplete: 12.

docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.1-cli php -d memory_limit=256M ./bin/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
Tests: 9275, Assertions: 39312, Errors: 124, Failures: 1, Skipped: 490, Incomplete: 12.

docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp phpdaily/php:8.2 php -d memory_limit=256M ./bin/phpunit --bootstrap tests/TestHelper.php tests/Zend/AllTests.php
Tests: 9275, Assertions: 30608, Errors: 2955, Failures: 4, Skipped: 448, Incomplete: 8.
```

So still some work to do, but at least we have something usable and future proof

**Comment by kaktusas2598** [comment]
I am currently testing this on our own platform, will come back with the results.

**Comment by Jimbolino** [comment]
[kaktusas2598](https://github.com/kaktusas2598) any update on this?
php 8.2 is ready in a couple days, so it would be great if we have some future proof tests before that day

**Comment by kaktusas2598** [comment]
@Jimbolino I ran the builds on our private servers and they are passing for us, but I can't guarantee this will work for everyone though, do you have any resources available to this for yourself as well? 

I think I will probably merge this anyway, agreed @Shardj ?

**Comment by Shardj** [comment]
@kaktusas2598 go for it

**Comment by develart-projects** [comment]
PHP8 - related problems are gone, getting this now:

`"/usr/bin/php" "/usr/bin/phpunit" "--colors" "--log-junit" "/tmp/nb-phpunit-log.xml" "--configuration" "/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml" "/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php"

PHP Fatal error:  Uncaught Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php:29
Stack trace:
Fatal error: Uncaught Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29

#0 /usr/share/php/PHPUnit/Util/Fileloader.php(52): include_once()
Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29

Call Stack:
    0.0003     361416   1. {main}() /usr/bin/phpunit:0
    0.0075     377040   2. PHPUnit_TextUI_Command::main($exit = ???) /usr/bin/phpunit:50
#1 /usr/share/php/PHPUnit/Util/Fileloader.php(36): PHPUnit_Util_Fileloader::load('/usr/share/NetB...')
#2 /usr/share/php/PHPUnit/TextUI/Command.php(914): PHPUnit_Util_Fileloader::checkAndLoad('/usr/share/NetB...')
    0.0075     377152   3. PHPUnit_TextUI_Command->run($argv = [0 => '/usr/bin/phpunit', 1 => '--colors', 2 => '--log-junit', 3 => '/tmp/nb-phpunit-log.xml', 4 => '--configuration', 5 => '/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml', 6 => '/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php'], $exit = TRUE) /usr/share/php/PHPUnit/TextUI/Command.php:116
    0.0075     377152   4. PHPUnit_TextUI_Command->handleArguments($argv = [0 => '/usr/bin/phpunit', 1 => '--colors', 2 => '--log-junit', 3 => '/tmp/nb-phpunit-log.xml', 4 => '--configuration', 5 => '/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml', 6 => '/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php']) /usr/share/php/PHPUnit/TextUI/Command.php:127
#3 /usr/share/php/PHPUnit/TextUI/Command.php(739): PHPUnit_TextUI_Command->handleBootstrap('/usr/share/NetB...')
    0.0141     384080   5. PHPUnit_TextUI_Command->handleBootstrap($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/./TestHelper.php') /usr/share/php/PHPUnit/TextUI/Command.php:739
    0.0143     384160   6. PHPUnit_Util_Fileloader::checkAndLoad($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/./TestHelper.php') /usr/share/php/PHPUnit/TextUI/Command.php:914
#4 /usr/share/php/PHPUnit/TextUI/Command.php(127): PHPUnit_TextUI_Command->handleArguments(Array)
    0.0143     384256   7. PHPUnit_Util_Fileloader::load($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php') /usr/share/php/PHPUnit/Util/Fileloader.php:36
#5 /usr/share/php/PHPUnit/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#6 /usr/bin/phpunit(50): PHPUnit_TextUI_Command::main()
#7 {main}
  thrown in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29
    0.0145     385432   8. include_once('/usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php') /usr/share/php/PHPUnit/Util/Fileloader.php:52


Variables in local scope (#8):
  $path = *uninitialized*
  $phpunitVersion = *uninitialized*
  $zfCoreLibrary = *uninitialized*
  $zfCoreTests = *uninitialized*
  $zfRoot = *uninitialized*

Done.`

**Comment by hungtrinh** [comment]
> PHP8 - related problems are gone, getting this now:
> 
> ```
> "/usr/bin/php" "/usr/bin/phpunit" "--colors" "--log-junit" "/tmp/nb-phpunit-log.xml" "--configuration" "/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml" "/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php"
> 
> PHP Fatal error:  Uncaught Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php:29
> Stack trace:
> Fatal error: Uncaught Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29
> 
> #0 /usr/share/php/PHPUnit/Util/Fileloader.php(52): include_once()
> Error: Class "PHPUnit\Runner\Version" not found in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29
> 
> Call Stack:
>     0.0003     361416   1. {main}() /usr/bin/phpunit:0
>     0.0075     377040   2. PHPUnit_TextUI_Command::main($exit = ???) /usr/bin/phpunit:50
> #1 /usr/share/php/PHPUnit/Util/Fileloader.php(36): PHPUnit_Util_Fileloader::load('/usr/share/NetB...')
> #2 /usr/share/php/PHPUnit/TextUI/Command.php(914): PHPUnit_Util_Fileloader::checkAndLoad('/usr/share/NetB...')
>     0.0075     377152   3. PHPUnit_TextUI_Command->run($argv = [0 => '/usr/bin/phpunit', 1 => '--colors', 2 => '--log-junit', 3 => '/tmp/nb-phpunit-log.xml', 4 => '--configuration', 5 => '/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml', 6 => '/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php'], $exit = TRUE) /usr/share/php/PHPUnit/TextUI/Command.php:116
>     0.0075     377152   4. PHPUnit_TextUI_Command->handleArguments($argv = [0 => '/usr/bin/phpunit', 1 => '--colors', 2 => '--log-junit', 3 => '/tmp/nb-phpunit-log.xml', 4 => '--configuration', 5 => '/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml', 6 => '/var/lib/snapd/snap/netbeans/69/netbeans/php/phpunit/NetBeansSuite.php']) /usr/share/php/PHPUnit/TextUI/Command.php:127
> #3 /usr/share/php/PHPUnit/TextUI/Command.php(739): PHPUnit_TextUI_Command->handleBootstrap('/usr/share/NetB...')
>     0.0141     384080   5. PHPUnit_TextUI_Command->handleBootstrap($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/./TestHelper.php') /usr/share/php/PHPUnit/TextUI/Command.php:739
>     0.0143     384160   6. PHPUnit_Util_Fileloader::checkAndLoad($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/./TestHelper.php') /usr/share/php/PHPUnit/TextUI/Command.php:914
> #4 /usr/share/php/PHPUnit/TextUI/Command.php(127): PHPUnit_TextUI_Command->handleArguments(Array)
>     0.0143     384256   7. PHPUnit_Util_Fileloader::load($filename = '/usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php') /usr/share/php/PHPUnit/Util/Fileloader.php:36
> #5 /usr/share/php/PHPUnit/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
> #6 /usr/bin/phpunit(50): PHPUnit_TextUI_Command::main()
> #7 {main}
>   thrown in /usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php on line 29
>     0.0145     385432   8. include_once('/usr/share/NetBeansProjects/ZF1-Future/tests/TestHelper.php') /usr/share/php/PHPUnit/Util/Fileloader.php:52
> 
> 
> Variables in local scope (#8):
>   $path = *uninitialized*
>   $phpunitVersion = *uninitialized*
>   $zfCoreLibrary = *uninitialized*
>   $zfCoreTests = *uninitialized*
>   $zfRoot = *uninitialized*
> 
> Done.
> ```

@develart-projects  It's about to autoload problem, so please set phpunit binary path on netbean point to **path_to_zf1_future/bin/phpunit** or point to [PHPUnit 9.5.21.phar downloaded on your computer](https://phar.phpunit.de/phpunit-9.5.21.phar) 

But i think this way it's better
```bash
cd path_to_zf1_future
./bin/phpunit -c tests/phpunit.xml tests/Zend/AllTests.php
```

**Comment by develart-projects** [comment]
Finally got it running, thanks:
`"/usr/bin/php" "/usr/share/NetBeansProjects/ZF1-Future/bin/phpunit" "--colors" "--log-junit" "/tmp/nb-phpunit-log.xml" "--configuration" "/usr/share/NetBeansProjects/ZF1-Future/tests/phpunit.xml" "/usr/share/NetBeansProjects/ZF1-Future/tests/AllTests.php"`

Now I need to strip deprecation messages :)
`PHP Deprecated:  Function mcrypt_module_close() is deprecated in /usr/share/NetBeansProjects/ZF1-Future/library/Zend/Filter/Encrypt/Mcrypt.php on line 311`

..writing that down here, so if anyone run into same troubles, google will help.

**Pull request merged**
