### PR TITLE
Various fixes for PHP 8.0 compatibility

### PR DESCRIPTION
**Pull request by onlime**
mainly backported from zf1s/zf1#32 PR by @Megatherium - thx for your great work!
see #120

### CODE REVIEW

**Comment by Shardj** [comment]
I'll go and make a major release for this now, thanks for the PR!

**Comment by glensc** [comment]
major release is 2.x not 1.19.x, see semver:
- https://semver.org/spec/v2.0.0.html

**Comment by Shardj** [comment]
Hm, I haven't strictly been following that if I'm being honest. I'm too used to my companies four digit internal version numbering system where "major" is the second digit and "epoch" is the first. I guess I should've updated to 2.0 after we stopped supporting versions before PHP 7.0 since we're following semvar format here. Nothing should've been changed in the 1.19.0 that would break backwards compatibility. Would you recommend updating straight to 2.0 anyway? @glensc

**Comment by onlime** [comment]
> Hm, I haven't strictly been following that if I'm being honest. I'm too used to my companies four digit internal version numbering system where "major" is the second digit and "epoch" is the first. I guess I should've updated to 2.0 after we stopped supporting versions before PHP 7.0 since we're following semvar format here. Nothing should've been changed in the 1.19.0 that would break backwards compatibility. Would you recommend updating straight to 2.0 anyway? @glensc

just m 5 cents: You picked up the initial ZF1 version scheme when you forked the project. So I would never jump to any 2.x version, as that could be really confusing - the **1.x** still stands for ZF**1**. So, even if not correct according to semver, you could talk about a "major release" if you release 1.19, 1.20,... and everybody will understand. We're also used to other minor releases that are actually really major releases... (thinking at Apple that got stuck on OSX/macOS 10.x for 15 years)

**Comment by glensc** [comment]
@Shardj: I just suggest not to say major version, while it's just 1.19. if the terminology is confusing just say the version itself out, avoid the terms epoch, major, minor, patch.

@onlime: I disagree here, zf1 is product name (actually even zf1-future), it has own versioning scheme. so it's fine to have zf1-future release 96.10.8.1 :) or with calver scheme 2021.01 :)

@Shardj: (so far) it's also valid to bump php in dependency in composer.json and do not make major release. composer will just ignore those versions where php runtime can't be matched. semver defines api compatibility, not runtime compatibility. there's tons of discussion on that topic. think this is the most recent topic; https://github.com/semver/semver/pull/546

**Pull request merged**
