### PR TITLE
Comment out require_once

### PR DESCRIPTION
**Pull request by techi602**
Since this was already requested in closed issue
https://github.com/Shardj/zf1-future/issues/37

require_once brings extra performance overhead and it is not needed if you install zf1 via composer.
I can't imagine anyone using this repository without one. 

I have decided to prepare the pull request

here is the shell script I have used - i keep the require_once line for better readability and issues with conflicts

```

  #!/bin/bash

  # find all php files in the current directory and its subdirectories
  find . -name "*.php" -print0 | while IFS= read -r -d '' file; do
    # comment out all lines starting with "require_once"
    sed -i '/^require_once/s/^/\/\/ /' "$file"
  done
```

Use classmap in your project in order to generate faster class loading, exclude classes you don't need. 

composer example with classmap:
```
"autoload": {
    "classmap": [
      "data/vendor/shardj/zf1-future/library"
    ],
    "exclude-from-classmap": [
      "data/vendor/shardj/zf1-future/library/Zend/Amf",
      "data/vendor/shardj/zf1-future/library/Zend/Cloud",
      "data/vendor/shardj/zf1-future/library/Zend/Dojo",
      "data/vendor/shardj/zf1-future/library/Zend/Gdata",
      "data/vendor/shardj/zf1-future/library/Zend/Pdf",
      "data/vendor/shardj/zf1-future/library/Zend/Search/Lucene",
      "data/vendor/shardj/zf1-future/library/Zend/Service",
      "data/vendor/shardj/zf1-future/library/Zend/Tool"
    ]
  },
```

### CODE REVIEW

**Comment by techi602** [comment]
looks like autoloading is not working in tests, let me check it first

**Comment by hungtrinh** [comment]
Think about back compatibility, old project don't use composer (download and extract latest Zend.latest.zip version to library/Zend) then `Comment out require_once` may not be good.

FYI , Current CI use phpunit binary (prepaired) to run test, don't run `composer install` so `vendor` doesn't exist

**Comment by glensc** [comment]
this breaks the compatibility of projects using true zf1 as @hungtrinh already pointed out, if you want to omit `require_once` calls and use composer, try https://github.com/zf1s/zf1 project.

**Comment by PHPGangsta** [comment]
I also use zf1-future as a drop-in replacement. I cannot use composer in this case because I have to apply a few patches to the zf1-future source code, which I cannot do if I install it via composer into the vendor/ folder (which is not part of the git repo).

Please don't assume everyone can use composer. Of cause it should be used as much as possible, but there are rare cases where you need the zip-archive and you cannot use composer autoloading.

**Pull request closed without merging**
