### PR TITLE
Fixed "emails are displayed incorrectly" with PHP 8.1+

### PR DESCRIPTION
**Pull request by fballiano**
This PR should fix issue https://github.com/Shardj/zf1-future/issues/274 and issue https://github.com/OpenMage/magento-lts/issues/3174 in OpenMage.

EDIT: this PR ports the fix used by laminas in https://github.com/laminas/laminas-mail/blob/2.23.x/src/Transport/Sendmail.php#L142-L147

### CODE REVIEW

**Review by kiatng — APPROVED** [review]
Tested on PHP7.3 and PHP8, Linux.

**Review by ADDISON74 — APPROVED** [review]

**Comment by ADDISON74** [comment]
I used DDEV and as PHP versions 7.4, 8 and 8.1. No issuess occurred. What was reported related to OpenMage is now resolved.

**Comment by glensc** [comment]
Is this fixed in zendframework 2 and/or laminas the same way?

**Comment by fballiano** [comment]
i've no idea, I don't know much about those two

**Comment by glensc** [comment]
those are both successors of zf1, so they might have fixed this too.

this may safe change, i.e change for all users, could break some other agents:
- https://github.com/PHPMailer/PHPMailer/issues/2870

you probably should set the property yourself, as it's public property,
unless you find they have fixed it same way or some rfc supports that \r\n must be used or PHP 8.1 own docs?

**Comment by fballiano** [comment]
since multiple people in https://github.com/Shardj/zf1-future/issues/274 are facing this problem I think it should be fixed at a framework level anyway.

**Comment by fballiano** [comment]
There's also this: https://github.com/php/php-src/issues/8086

**Comment by kiatng** [comment]
Know nothing about Laminas, but the fix is different. First, the `EOL` const is defined same as this PR:

https://github.com/laminas/laminas-mail/blob/2.23.x/src/Headers.php#L51
image

Second, it is converted to `"\n"` for WIN OS:

https://github.com/laminas/laminas-mail/blob/2.23.x/src/Transport/Sendmail.php#L142-L147
image

This PR doesn't check for WIN OS and PHP ver.

**Comment by glensc** [comment]
> since multiple people in https://github.com/Shardj/zf1-future/issues/274 are facing this problem I think it should be fixed at a framework level anyway.

this not a good excuse. because if this is a breaking change the rest of the users start to complain for whom it worked before.

**Comment by fballiano** [comment]
did you check https://github.com/php/php-src/issues/8086?

I see the worry about the possible BC, but not doing anything is BC for an opposite equal amount of people...

**Comment by fballiano** [comment]
would you like a PR which is more similar to laminas?

**Comment by ADDISON74** [comment]
@glensc - My personal opinion is that ZF1-Future must have the source code related to this issue similar to Laminas-Mail. It is obvious that this change is necessary, but the one in Laminas-Mail covers all the issues that could arise with its adoption.

**Comment by glensc** [comment]
I've read along:
- https://github.com/php/php-src/issues/8086

mostly people are frustrated by the change, but PHP devs say \r\n is standards conformant. but really standards is for smtp saying must be \r\n terminated, no standard how one should talk to /usr/lib/sendmail.

perhaps introduce similar behavior to:
-https://github.com/php/php-src/pull/10191

i.e respect `mail.mixed_lf_and_crlf` in setting, so if that option is set, go back to previous behavior otherwise go with \r\n.
must consider that the option may be missing on older PHP versions.

not sure what is "similar to laminas", you just linked to a line. maybe commit or pull request making the change has more context?

**Comment by fballiano** [comment]
Most similar to laminas i mean the code posted by @kiatng obviously.

I’m doing it if you’ll consider it, otherwise I’ll check other solutions internally, sorry but time is precious for everybody.

**Comment by glensc** [comment]
phpmailer seems has taken totally different approach. tells to use smtp rather sendmail driver:
- https://github.com/PHPMailer/PHPMailer/issues/2870#issuecomment-1419897221

:)

**Comment by glensc** [comment]
php `mail()` and `mb_send_mail()` also say (now) to use \r\n, and as last result fall back to \n:
- https://www.php.net/manual/en/function.mail.php
- https://www.php.net/manual/en/function.mb-send-mail.php

**Comment by glensc** [comment]
Seems checking `mail.mixed_lf_and_crlf` is not a viable solution. it's not present in any release PHP version

```
php -d mail.mixed_lf_and_crlf=1 -r 'var_dump([ini_get("mail.mixed_lf_and_crlf"), PHP_VERSION]);'        
array(2) {
  [0]=>
  bool(false)
  [1]=>
  string(5) "8.2.3"
}
```

See also:
- https://stackoverflow.com/questions/70502065/php8-mail-function-adding-space-prefixes-to-headers/75317793#75317793
- https://github.com/php/php-src/issues/8086#issuecomment-1414476586
- https://github.com/php/php-src/pull/10191
- https://www.php.net/manual-lookup.php?pattern=mail.mixed_lf_and_crlf&scope=quickref - docs not found

**Comment by glensc** [comment]
@fballiano laminas way is the recommended solution, I said as first note here:
- https://github.com/Shardj/zf1-future/pull/344#issuecomment-1512749020

likely battle-tested by them as the changes already seem 3yr old.

but it may be more changes than just those lines printed here:
- https://github.com/Shardj/zf1-future/pull/344#issuecomment-1512841520

**Comment by fballiano** [comment]
I rewrote the PR, not sure about the $fromEmailHeader, which shouldn't contain an EOL anyway...

**Comment by glensc** [comment]
What abuot EOL constant? in zf2/laminas it's there since 2012:
- https://github.com/zendframework/zendframework/commit/5f899d3d20a8c3d581f6e86b3ba038797e1d4e08#diff-cd2e235ede76dad36d06a755991777edb55781b2fc4321c74fb7d17605522834

Describe your changes and thinking logic in PR body.

**Comment by fballiano** [comment]
I see no other EOL constant in the Zend/Mail folder.

**Comment by ADDISON74** [comment]
I guess @glensc wants to use self::EOL instead of "\r\n".

**Comment by glensc** [comment]
Indeed, somehow I looked only the new commit, and assumed it was force pushed, but the original commit is still here:
- [`48ad3c3` (#344)](https://github.com/Shardj/zf1-future/pull/344/commits/48ad3c3049384949d33928f4a7cbe1fa535a84da)

**Comment by fballiano** [comment]
I’d keep it this way in case somebody extends the class. I think it’s the same thought the laminas people did

**Review by ADDISON74 — APPROVED** [review]

**Comment by fballiano** [comment]
any news on the merge of this PR?

**Comment by develart-projects** [comment]
@fballiano I'll review that in comming days, now focusing on the bugfix release.

**Comment by develart-projects** [comment]
Checked all information presented, I think we are good to go here.

**Pull request merged**
