### PR TITLE
Reduce unnecessary local variables

### PR DESCRIPTION
**Pull request by kstenschke**

### CODE REVIEW

**Comment by WebTigers** [comment]
I assume there was a reason for the local vars in earlier versions of PHP? This looks good to me as long as all of the tests pass for the supported versions of PHP 7.x. Not really any bug fixing here though. Just some nice code optimization.

**Comment by kstenschke** [comment]
_I assume there was a reason for the local vars in earlier versions of PHP?_
As there's no technical reason from PHP's prior versions, we can only speculate about the reasons. Maybe it's the evolved inspection tools and understanding of clean-code within the PHP community and ecosystem. However, when using automated code quality assurance tools, this changeset reduces the report by a 100+ code smells.

**Comment by glensc** [comment]
You could not return by reference in php4->php5 migration:

so, you had to write like:

```diff
function &returns_by_reference() {
-        return new Zend_Date($timestamp);
+        $value = new Zend_Date($timestamp);
+        return $value;
}
```

altho I think the variables are in current codebase just by code style and developer preference. altho very unlikely, you could git blame and maybe the reason is in commit message.

**Comment by Shardj** [comment]
Thanks for the pr

**Pull request merged**
